### ISSUE TITLE
登录失败，Get skey failed, restart login，网页版没问题

### ISSUE THREAD

**Issue by yknext** [coderafei/wechat-bot#13]
不知道项目是否还在维护，今天有个问题导致无法登陆了，应该是微信屏蔽了

Thu, 22 Jun 2017 03:21:22 GMT weixinbot 二维码已被扫描，请确认登录!
Thu, 22 Jun 2017 03:21:22 GMT weixinbot 二维码已被扫描，请确认登录!
Thu, 22 Jun 2017 03:21:22 GMT weixinbot 二维码已被扫描，请确认登录!
Thu, 22 Jun 2017 03:21:23 GMT weixinbot 已点击确认登录!
Thu, 22 Jun 2017 03:21:23 GMT weixinbot 正在获取凭据...
Thu, 22 Jun 2017 03:21:23 GMT weixinbot 鉴权失败，正在重新登录... Error: Get skey failed, restart login
    at WeixinBot._callee6$ (/opt/MessageBot/node_modules/._weixinbot@0.6.1@weixinbot/lib/weixinbot.js:675:23)
    at tryCatch (/opt/MessageBot/node_modules/._regenerator-runtime@0.10.5@regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/MessageBot/node_modules/._regenerator-runtime@0.10.5@regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/opt/MessageBot/node_modules/._regenerator-runtime@0.10.5@regenerator-runtime/runtime.js:117:21)
    at step (/opt/MessageBot/node_modules/._babel-runtime@6.23.0@babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /opt/MessageBot/node_modules/._babel-runtime@6.23.0@babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:109:7)
Thu, 22 Jun 2017 03:21:23 GMT weixinbot 开始登录...
Thu, 22 Jun 2017 03:21:23 GMT weixinbot 获得 uuid -> Qa0dRIxuRg==
https://login.weixin.qq.com/qrcode/Qa0dRIxuRg==
Thu, 22 Jun 2017 03:21:23 GMT weixinbot 发送二维码图片到邮箱 xxx
Thu, 22 Jun 2017 03:21:48 GMT weixinbot 检查登录超时，正在重试...

日志二

  weixinbot 二维码已被扫描，请确认登录! +50ms
  weixinbot 二维码已被扫描，请确认登录! +55ms
  weixinbot 二维码已被扫描，请确认登录! +40ms
  weixinbot 二维码已被扫描，请确认登录! +50ms
  weixinbot 已点击确认登录! +60ms
  weixinbot 正在获取凭据... +0ms
  weixinbot
  weixinbot       获得 skey -> @crypt_80d6c3a6_a2fcf8ccf3f7e96760cd0a00f6764aef2
  weixinbot       获得 sid -> HFMFnhGrfAYhRfKQe
  weixinbot       获得 uid -> 583576777
  weixinbot       获得 pass_ticket -> WWy1rGORbOAbvazmJR0DuGIQ6FCoiHEHGg2N1raFu77
cZIaXIawodZbSJtiqnHk0d
  weixinbot      +313ms
  weixinbot 获取凭据成功! +10ms
  weixinbot 开始循环拉取新消息 +0ms
  weixinbot 正在初始化参数... +0ms
  weixinbot 登录信息已失效，正在重新获取二维码...yyyyy +50ms
  weixinbot 开始登录... +0ms
  weixinbot 获得 uuid -> QaAtXo7CTA== +70ms
https://login.weixin.qq.com/qrcode/QaAtXo7CTA==

**Comment by feit** [comment]
有时间就更新，欢迎PR 😄

**Comment by yknext** [comment]
网页版也不行了，微信采取措施了

<error><ret>1203</ret><message>当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过手机客户端或者windows微信登录。</message></error>

**Comment by feit** [comment]
看来是全面开始封禁了
